image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      stack config set install-ghc false --global
      stack config set system-ghc true --global
      ghcup install ghc 9.0.2
    init: |
      cabal update
      stack build
    command: |
      stack test

vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
