image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      source /home/gitpod/.ghcup/env
      cabal update
      stack build

    command: |
      stack test

vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
